title: <p align="center"> Ankit Chandre </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="linkedin.com/in/ankit-chandre-36819750/">LinkedIn</a> |
  <a href="https://github.com/Ankitchandre">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>



theme: jekyll-theme-minimal
